# Custom Exceptions

Небольшое задание на применение пользовательских исключений.

В модуле **Homework** нужно реализовать 4 функции:

Функция **get_from_list!/2** принимает список и индекс. Она возвращает элемент списка по индексу или генерирует исключение **IndexOutOfBoundsError**, если index невалидный.

Функция **get_from_list/2** работает так же, но она возвращает кортеж `{:ok, result}` в успешном случае или кортеж `{:error, err_message}`, если index невалидный.

Функция **get_many_from_list!/2** принимает список из каких-то элементов и список индексов. Она возвращает новый список элементов, соответственно полученным индексам. 

Например: 

```elixir-iex
> Homework.get_many_from_list!(["cat", "dog", "fish"], [0, 0, 2, 2]) 
["cat", "cat", "fish", "fish"]
```

Функция **get_many_from_list/2** работает так же, но возвращает кортеж `{:ok, result}` в успешном случае или кортеж `{:error, err_message}`, если index не валидный.

Например:

```elixir-iex
> Homework.get_many_from_list(["cat", "dog", "fish"], [1, 0]) 
{:ok, ["dog", "cat"]}
```

Исключение **IndexOutOfBoundsError** нужно реализовать так, чтобы его message соответствовал формату `"index 42 is out of bounds [0-3)"`, где index и bounds должны соответствовать аргументам функций. Смотрите, какой message ожидается в тестах в разных случаях.
